### ISSUE TITLE
implementazione ampiezza su tutti i files

### ISSUE THREAD

**Issue by DavideTedesco** [LucaSpanedda/Faust-step-by-step#3]
forse puó risultare comodo implementare un controllo dell'ampiezza su tutti i programmi con un semplice _hslider_ o _vslider_ su ogni programmi, giusto per non sfondarsi le recchie ogni volta che si provano gli algoritmini, che ne pensi?

**Comment by LucaSpanedda** [comment]
Giusto. Fatto!
